name: Build GitHub Action

on:
  push:
    paths:
      - '.github/actions/get-prompt/**'
  pull_request:
    paths:
      - '.github/actions/get-prompt/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/actions/get-prompt
        
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '.github/actions/get-prompt/package-lock.json'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build action
        run: npm run build
      
      - name: Check dist/ is up to date
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi
        id: diff
      
      # If index.js was different than expected, upload the expected version as an artifact
      - uses: actions/upload-artifact@v4
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        with:
          name: dist
          path: .github/actions/get-prompt/dist/